import { DayStatus } from './romanCalendarData';

export interface YearDayEntry {
    status: DayStatus;
    statusFull: string;
    deity: string; // The "God of the Day" (Year Day)
    deityDesc: string; // Spanish description
    festivalName?: string;
    festivalDesc?: string;
}

// FORMAT: "Month-Day" (0-based month)
export const ROMAN_YEAR_DATA: Record<string, YearDayEntry> = {
    // --- IANUARIUS (JANUARY) ---
    "0-1": { status: 'F', statusFull: "Kalendae Ianuariae", deity: "Jano / Juno", deityDesc: "Dios de los inicios y diosa del mes.", festivalName: "Kalendae Ianuariae", festivalDesc: "Celebración del Año Nuevo romano dedicada a Jano. Durante el Imperio, los nuevos cónsules asumían su cargo y se realizaban votos públicos por el estado." },
    "0-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Lares Compitales", deityDesc: "Dioses protectores de las encrucijadas.", festivalName: "Compitalia (fecha probable)", festivalDesc: "Fiesta móvil (feriae conceptivae) tradicionalmente celebrada a principios de enero en los cruces de los caminos." },
    "0-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Lares Compitales", deityDesc: "Dioses protectores de las encrucijadas.", festivalName: "Compitalia", festivalDesc: "Continuación de las festividades en honor a los Lares." },
    "0-5": { status: 'F', statusFull: "Nonae", deity: "Vica Pota", deityDesc: "Antigua diosa de la victoria.", festivalName: "Dedicación del Templo de Vica Pota", festivalDesc: "Aniversario de la dedicación del santuario de esta diosa arcaica en la Velia." },
    "0-6": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-7": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-8": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-9": { status: 'NP', statusFull: "Agonalia", deity: "Jano", deityDesc: "Dios de los comienzos.", festivalName: "Agonalia", festivalDesc: "El Rex Sacrorum sacrifica un carnero en la Regia en honor a Jano." },
    "0-10": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-11": { status: 'NP', statusFull: "Carmentalia", deity: "Carmenta / Juturna", deityDesc: "Diosa del parto y ninfa de las fuentes.", festivalName: "Carmentalia / Juturnalia", festivalDesc: "Primer día de las fiestas de Carmenta, patrona de los partos, observada principalmente por matronas. También se honra a Juturna." },
    "0-12": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-13": { status: 'NP', statusFull: "Idus", deity: 'Júpiter', deityDesc: 'Rey de los dioses.', festivalName: "Idus de Enero", festivalDesc: "Día consagrado a Júpiter, marcado por el sacrificio de la ovis idulis (oveja de los idus)." },
    "0-14": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-15": { status: 'NP', statusFull: "Carmentalia II", deity: "Carmenta", deityDesc: "Diosa del parto.", festivalName: "Carmentalia", festivalDesc: "Segundo y último día de las fiestas de Carmenta." },
    "0-16": { status: 'C', statusFull: "Dies Comitialis", deity: "Concordia", deityDesc: "Diosa de la armonía civil.", festivalName: "Dedicación del Templo de la Concordia", festivalDesc: "Conmemoración del templo de Concordia erigido tras el fin de las antiguas luchas patricio-plebeyas." },
    "0-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-19": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-21": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-23": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Ceres y Tellus", deityDesc: "Diosas de la agricultura y la tierra.", festivalName: "Feriae Sementivae", festivalDesc: "Fiesta agrícola móvil de la siembra celebrada habitualmente a finales de enero para pedir protección para los cultivos." },
    "0-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ceres y Tellus", deityDesc: "Diosas agrícolas.", festivalName: "Feriae Sementivae", festivalDesc: "Continuación de los ritos agrícolas de la siembra." },
    "0-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ceres y Tellus", deityDesc: "Diosas agrícolas.", festivalName: "Feriae Sementivae", festivalDesc: "Finalización de los ritos de bendición de las semillas." },
    "0-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Cástor y Pólux", deityDesc: "Dioses gemelos.", festivalName: "Dedicación del Templo de Cástor y Pólux", festivalDesc: "Aniversario de la dedicación de su famoso templo en el Foro Romano." },
    "0-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-29": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "0-30": { status: 'F', statusFull: "Dies Fastus", deity: "Pax", deityDesc: "Diosa de la paz.", festivalName: "Dedicación del Ara Pacis", festivalDesc: "Conmemoración de la consagración del Altar de la Paz Augusta en el año 9 a.C." },
    "0-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },

    // --- FEBRUARIUS (FEBRUARY) ---
    "1-1": { status: 'NP', statusFull: "Kalendae", deity: "Juno Sospita", deityDesc: "Juno la Salvadora.", festivalName: "Dedicación del Templo de Juno", festivalDesc: "Aniversario del templo de Juno Sospita en Roma." },
    "1-2": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-3": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-4": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-5": { status: 'N', statusFull: "Nonae", deity: "Concordia", deityDesc: "Diosa de la armonía civil.", festivalName: "Dedicación del Templo de Concordia (Arx)", festivalDesc: "Aniversario de la dedicación del templo de Concordia ubicado en el Arx del Capitolio." },
    "1-6": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-7": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-8": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-9": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-10": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-11": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-12": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-13": { status: 'NP', statusFull: "Idus", deity: "Fauno", deityDesc: "Dios de la naturaleza y los rebaños.", festivalName: "Inicio de la Parentalia", festivalDesc: "Comienzan los días de reverencia privada a los difuntos de la familia (Parentalia). También sacrificios a Fauno en la isla Tiberina." },
    "1-14": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-15": { status: 'NP', statusFull: "Lupercalia", deity: "Fauno / Lupercus", deityDesc: "Antiguo dios rústico.", festivalName: "Lupercalia", festivalDesc: "Arcaico festival de purificación. Los sacerdotes Luperci corren alrededor de la colina Palatina con correas de piel de cabra." },
    "1-16": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-17": { status: 'NP', statusFull: "Quirinalia", deity: "Quirino / Fornax", deityDesc: "Dios del estado romano y diosa de los hornos.", festivalName: "Quirinalia / Fornacalia (Fin)", festivalDesc: "Día de Quirino. Sirve también como el último día (Feriae Stultorum) para los ritos de tostado de grano de la diosa Fornax." },
    "1-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-19": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-21": { status: 'NP', statusFull: "Feralia", deity: "Manes", deityDesc: "Espíritus de los ancestros.", festivalName: "Feralia", festivalDesc: "Día público de cierre de la Parentalia dedicado a apaciguar a los Manes y realizar ofrendas en las tumbas familiares. Día nefasto: toda actividad pública estaba prohibida." },
    "1-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Concordia Familiar", deityDesc: "Armonía entre parentela.", festivalName: "Caristia (Cara Cognatio)", festivalDesc: "Banquetes familiares donde se resolvían las disputas tras los días dedicados a los muertos." },
    "1-23": { status: 'NP', statusFull: "Terminalia", deity: "Terminus", deityDesc: "Dios de los límites.", festivalName: "Terminalia", festivalDesc: "Ritos celebrados en las piedras fronterizas que marcaban propiedades y fronteras para mantener el orden de la propiedad terrenal." },
    "1-24": { status: 'N', statusFull: "Regifugium", deity: "Ninguna", deityDesc: "Conmemoración cívico-religiosa.", festivalName: "Regifugium", festivalDesc: "El 'Vuelo del Rey'. Rito antiguo en el que el Rex Sacrorum realizaba un sacrificio y huía del Foro." },
    "1-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-26": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-27": { status: 'NP', statusFull: "Equirria", deity: "Marte", deityDesc: "Dios de la guerra.", festivalName: "Equirria", festivalDesc: "Primera de las carreras de carros y caballos en el Campo de Marte, dedicadas al dios antes de la temporada militar." },
    "1-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "1-29": { status: 'C', statusFull: "Dies Bissextus", deity: "Ninguna", deityDesc: "Día intercalar romano.", festivalName: "Dies Bissextus", festivalDesc: "Día añadido en el calendario juliano en años bisiestos (bis sextus dies ante calendas martias)." },

    // --- MARTIUS (MARCH) ---
    "2-1": { status: 'NP', statusFull: "Kalendae", deity: "Marte / Juno Lucina", deityDesc: "Dios de la guerra y diosa del parto.", festivalName: "Feriae Marti / Matronalia", festivalDesc: "Original Año Nuevo del calendario de Rómulo. Comienzan las procesiones de los sacerdotes Salii y las esposas celebran la Matronalia." },
    "2-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-5": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-6": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-7": { status: 'F', statusFull: "Nonae", deity: "Vediovis", deityDesc: "Deidad itálica arcaica.", festivalName: "Sacrificio a Vediovis", festivalDesc: "Festividad dedicada a Vediovis en la colina del Capitolio." },
    "2-8": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-9": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-10": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-11": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-12": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-13": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-14": { status: 'NP', statusFull: "Equirria II", deity: "Marte", deityDesc: "Dios de la guerra.", festivalName: "Segunda Equirria", festivalDesc: "Segunda fecha de carreras de caballos sagradas en el Campo de Marte para honrar y purificar a las monturas militares." },
    "2-15": { status: 'NP', statusFull: "Idus Martiae", deity: "Anna Perenna / Júpiter", deityDesc: "Diosa del año y dios supremo.", festivalName: "Anna Perenna", festivalDesc: "Fiesta popular a orillas del Tíber bebiendo vino para asegurar una larga vida. Históricamente marcado por el asesinato de Julio César (44 a.C.)." },
    "2-16": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Cultos de purificación.", festivalName: "Itinerario de los Argei", festivalDesc: "Primera procesión del año recorriendo las 27 antiguas capillas de los Argei repartidas por Roma." },
    "2-17": { status: 'NP', statusFull: "Liberalia / Agonalia", deity: "Liber Pater / Marte", deityDesc: "Dios del vino y de la guerra.", festivalName: "Liberalia", festivalDesc: "Se celebra el crecimiento de la juventud; los adolescentes romanos asumen la Toga Virilis (ropa de adultez civil)." },
    "2-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-19": { status: 'NP', statusFull: "Quinquatrus", deity: "Minerva", deityDesc: "Diosa de las artes y la estrategia militar.", festivalName: "Quinquatrus", festivalDesc: "Gran festividad dedicada a Minerva y popular entre artesanos, educadores y estudiantes. Se purificaban también las armas." },
    "2-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Minerva", deityDesc: "Diosa de las artes.", festivalName: "Ludi de Minerva", festivalDesc: "Días posteriores de la Quinquatría, a menudo acompañados de juegos gladiatorios." },
    "2-21": { status: 'C', statusFull: "Dies Comitialis", deity: "Minerva", deityDesc: "Diosa de las artes.", festivalName: "Ludi de Minerva", festivalDesc: "Prosiguen los eventos de la Quinquatrus." },
    "2-22": { status: 'N', statusFull: "Dies Nefastus", deity: "Minerva", deityDesc: "Diosa de las artes.", festivalName: "Ludi de Minerva", festivalDesc: "Conclusión de los juegos principales en honor a Minerva." },
    "2-23": { status: 'NP', statusFull: "Tubilustrium", deity: "Marte", deityDesc: "Dios de la guerra.", festivalName: "Tubilustrium", festivalDesc: "Ceremonia de purificación de las trompetas sagradas y militares (tubae), marcando la preparación final para la temporada de campañas." },
    "2-24": { status: 'F', statusFull: "QRCF", deity: "Ninguna", deityDesc: "Rito del rey sagrado.", festivalName: "Quando Rex Comitiavit Fas", festivalDesc: "El Rey Sagrado (Rex Sacrorum) asiste al comicio. Una vez que concluían sus ritos formales, el resto del día volvía a ser lícito (Fas)." },
    "2-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "2-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Luna", deityDesc: "Diosa de la luna.", festivalName: "Dedicación del Templo de Luna", festivalDesc: "Aniversario del templo de la Luna ubicado en el monte Aventino." },

    // --- APRILIS (APRIL) ---
    "3-1": { status: 'F', statusFull: "Veneralia", deity: "Venus Verticordia", deityDesc: "Venus, la que vuelve los corazones.", festivalName: "Veneralia", festivalDesc: "Las mujeres bañaban ritualmente la estatua de Venus y rogaban que sus corazones se mantuvieran fieles hacia la virtud y el honor marital." },
    "3-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-4": { status: 'NP', statusFull: "Megalesia", deity: "Magna Mater", deityDesc: "Cibeles, la Gran Madre de los Dioses.", festivalName: "Megalesia", festivalDesc: "Inicio de los grandes Ludi Megalenses. Los devotos asistían a representaciones teatrales en honor a la deidad oriental adoptada por Roma." },
    "3-5": { status: 'NP', statusFull: "Nonae", deity: "Fortuna Publica / Magna Mater", deityDesc: "La fortuna del estado y Cibeles.", festivalName: "Megalesia / Templo de Fortuna", festivalDesc: "Continúan los juegos. Se celebraba también el aniversario de la dedicación del templo de Fortuna Publica." },
    "3-6": { status: 'NP', statusFull: "Megalesia", deity: "Magna Mater", deityDesc: "Cibeles.", festivalName: "Megalesia", festivalDesc: "Prosiguen las representaciones teatrales de los Megalesia." },
    "3-7": { status: 'NP', statusFull: "Megalesia", deity: "Magna Mater", deityDesc: "Cibeles.", festivalName: "Megalesia", festivalDesc: "Cuarto día de los Megalesia." },
    "3-8": { status: 'NP', statusFull: "Megalesia", deity: "Magna Mater", deityDesc: "Cibeles.", festivalName: "Megalesia", festivalDesc: "Continuación de los Ludi Megalenses." },
    "3-9": { status: 'NP', statusFull: "Megalesia", deity: "Magna Mater", deityDesc: "Cibeles.", festivalName: "Megalesia", festivalDesc: "Penúltimo día de las festividades de Cibeles." },
    "3-10": { status: 'NP', statusFull: "Megalesia", deity: "Magna Mater", deityDesc: "Cibeles.", festivalName: "Fin de Megalesia", festivalDesc: "Conclusión de los juegos en honor a la Magna Mater." },
    "3-11": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-12": { status: 'NP', statusFull: "Cerialia", deity: "Ceres", deityDesc: "Diosa de la agricultura.", festivalName: "Cerialia", festivalDesc: "Inician los Ludi Ceriales para fomentar el crecimiento del cereal. Las festividades incluían obras de teatro y el uso ropas blancas." },
    "3-13": { status: 'NP', statusFull: "Idus", deity: "Júpiter Victor", deityDesc: "Júpiter victorioso.", festivalName: "Idus de Abril", festivalDesc: "Dedicación del templo de Júpiter Victor. Continúan los Juegos de Ceres." },
    "3-14": { status: 'N', statusFull: "Dies Nefastus", deity: "Ceres", deityDesc: "Diosa agrícola.", festivalName: "Cerialia", festivalDesc: "Prosiguen los juegos de Ceres." },
    "3-15": { status: 'NP', statusFull: "Fordicidia", deity: "Tellus", deityDesc: "La Tierra.", festivalName: "Fordicidia", festivalDesc: "Sacrificio de vacas preñadas a Tellus (Madre Tierra) para potenciar la fertilidad del suelo romano en primavera." },
    "3-16": { status: 'N', statusFull: "Dies Nefastus", deity: "Ceres", deityDesc: "Diosa agrícola.", festivalName: "Cerialia", festivalDesc: "Continuación de los juegos para Ceres." },
    "3-17": { status: 'N', statusFull: "Dies Nefastus", deity: "Ceres", deityDesc: "Diosa agrícola.", festivalName: "Cerialia", festivalDesc: "Continúan los eventos teatrales de la Cerialia." },
    "3-18": { status: 'N', statusFull: "Dies Nefastus", deity: "Ceres", deityDesc: "Diosa agrícola.", festivalName: "Cerialia", festivalDesc: "Prosiguen los eventos teatrales de la Cerialia." },
    "3-19": { status: 'NP', statusFull: "Cerialia", deity: "Ceres", deityDesc: "Diosa agrícola.", festivalName: "Cerialia (Fin)", festivalDesc: "Culminación de los Juegos de Ceres. Ovidio reporta la práctica ritual de soltar zorros con antorchas encendidas en el Circo Máximo." },
    "3-20": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-21": { status: 'NP', statusFull: "Parilia", deity: "Pales", deityDesc: "Diosa de los pastores.", festivalName: "Parilia / Natalis Romae", festivalDesc: "Festival pastoral de purificación de los rebaños, considerado tradicionalmente como el aniversario de la fundación mítica de Roma (Dies Natalis)." },
    "3-22": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-23": { status: 'NP', statusFull: "Vinalia Priora", deity: "Venus / Júpiter", deityDesc: "Diosa del amor y dios supremo.", festivalName: "Vinalia Priora", festivalDesc: "Primera celebración anual del vino. El vino del año anterior era abierto y se ofrecían las libaciones a Júpiter." },
    "3-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-25": { status: 'NP', statusFull: "Robigalia", deity: "Robigo", deityDesc: "Deidad de las plagas agrícolas.", festivalName: "Robigalia", festivalDesc: "El flamen Quirinalis sacrificaba un animal de pelaje rojo para apaciguar al dios/diosa del mildiu y rogar que no oxidara el trigo incipiente." },
    "3-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "3-28": { status: 'NP', statusFull: "Floralia", deity: "Flora", deityDesc: "Diosa de las flores.", festivalName: "Floralia", festivalDesc: "Inicio de los Ludi Florales, fiestas bulliciosas y alegres celebrando la fertilidad de las flores en desarrollo." },
    "3-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Flora", deityDesc: "Diosa de las flores.", festivalName: "Floralia", festivalDesc: "Continúan los juegos de Flora." },
    "3-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Flora", deityDesc: "Diosa de las flores.", festivalName: "Floralia", festivalDesc: "Prosiguen los juegos licenciosos y celebraciones al aire libre de Flora." },

    // --- MAIUS (MAY) ---
    "4-1": { status: 'NP', statusFull: "Kalendae", deity: "Bona Dea / Lares Praestites", deityDesc: "Diosa buena y guardianes cívicos.", festivalName: "Dedicaciones / Floralia", festivalDesc: "Ofrendas a los Lares de la ciudad y aniversario del templo de la Bona Dea. Continúan los Ludi de Flora." },
    "4-2": { status: 'F', statusFull: "Dies Fastus", deity: "Flora", deityDesc: "Diosa de las flores.", festivalName: "Floralia", festivalDesc: "Continuación de las festividades de Flora." },
    "4-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Flora", deityDesc: "Diosa de las flores.", festivalName: "Fin de Floralia", festivalDesc: "Conclusión de los juegos florales." },
    "4-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-5": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-6": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-7": { status: 'F', statusFull: "Nonae", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-8": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-9": { status: 'NP', statusFull: "Lemuria", deity: "Lemures", deityDesc: "Espíritus de los muertos.", festivalName: "Lemuria", festivalDesc: "Primer día de los ritos arcaicos de propiciación familiar. El paterfamilias arrojaba habas negras a sus espaldas en la noche para aplacar a los espíritus." },
    "4-10": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-11": { status: 'NP', statusFull: "Lemuria", deity: "Lemures", deityDesc: "Espíritus de los muertos.", festivalName: "Lemuria", festivalDesc: "Segundo día de ritos de expiación a los muertos." },
    "4-12": { status: 'NP', statusFull: "Ludi Martiales", deity: "Mars Ultor", deityDesc: "Marte Vengador.", festivalName: "Dedicación del Templo de Marte Ultor", festivalDesc: "Juegos en el Circo que conmemoran la dedicación del templo de Marte en el foro de Augusto (2 a.C.)." },
    "4-13": { status: 'NP', statusFull: "Lemuria", deity: "Lemures", deityDesc: "Espíritus de los muertos.", festivalName: "Lemuria", festivalDesc: "Último día de ritos nocturnos de la Lemuria." },
    "4-14": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica.", festivalName: "Ritos de los Argei", festivalDesc: "Procesión sagrada. Las vírgenes vestales arrojan efigies de paja llamadas 'Argei' a las aguas del río Tíber." },
    "4-15": { status: 'NP', statusFull: "Idus / Mercuralia", deity: "Mercurio / Júpiter", deityDesc: "Dios del comercio / Dios supremo.", festivalName: "Mercuralia", festivalDesc: "Día de los Idus. Los comerciantes pedían a Mercurio protección para sus negocios y perdón por las transgresiones comerciales." },
    "4-16": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-19": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-21": { status: 'NP', statusFull: "Agonalia", deity: "Vediovis", deityDesc: "Antigua deidad.", festivalName: "Agonalia", festivalDesc: "Día de sacrificio especial consagrado a Vediovis." },
    "4-22": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-23": { status: 'NP', statusFull: "Tubilustrium", deity: "Vulcano", deityDesc: "Dios del fuego y la forja.", festivalName: "Tubilustrium", festivalDesc: "Segunda purificación anual de las trompetas sagradas (tubae), dedicadas a Vulcano." },
    "4-24": { status: 'F', statusFull: "QRCF", deity: "Ninguna", deityDesc: "Rito del rey sagrado.", festivalName: "Quando Rex Comitiavit Fas", festivalDesc: "El Rex Sacrorum completaba sus deberes religiosos." },
    "4-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Fortuna Primigenia", deityDesc: "Fortuna original.", festivalName: "Dedicación del Templo de Fortuna Primigenia", festivalDesc: "Celebración cívica de la Fortuna Original de la colina Quirinal." },
    "4-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Deidades agrarias", deityDesc: "Ritos del campo.", festivalName: "Ambarvalia", festivalDesc: "Feriae conceptivae. Purificación de las tierras agrícolas marchando a lo largo de los límites con víctimas sacrificiales (suovetaurilia)." },
    "4-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "4-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },

    // --- IUNIUS (JUNE) ---
    "5-1": { status: 'NP', statusFull: "Kalendae", deity: "Carna / Juno Moneta", deityDesc: "Diosas protectoras.", festivalName: "Kalendae Fabariae", festivalDesc: "Sacrificio de habas a Carna, protectora de la vitalidad del cuerpo. También aniversario del templo de Juno Moneta." },
    "5-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Bellona", deityDesc: "Diosa de la guerra.", festivalName: "Dedicación del Templo de Bellona", festivalDesc: "Aniversario de la dedicación del templo en el Campo de Marte (296 a.C.)." },
    "5-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Hercules Custos", deityDesc: "Hércules Guardián.", festivalName: "Dedicación del Templo de Hércules", festivalDesc: "Dedicación del templo de Hercules Custos." },
    "5-5": { status: 'F', statusFull: "Nonae", deity: "Semo Sancus Dius Fidius", deityDesc: "Dios de los juramentos.", festivalName: "Dedicación del Templo de Dius Fidius", festivalDesc: "Fiesta y conmemoración de Semo Sancus, garante de la fides (lealtad y juramentos)." },
    "5-6": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-7": { status: 'N', statusFull: "Dies Nefastus", deity: "Tiberinus", deityDesc: "Dios del río Tíber.", festivalName: "Ludi Piscatorii", festivalDesc: "Los pescadores del Tíber realizaban ofrendas religiosas formales de sus capturas." },
    "5-8": { status: 'N', statusFull: "Dies Nefastus", deity: "Mens", deityDesc: "Diosa del pensamiento y el intelecto.", festivalName: "Dedicación del Templo de Mens", festivalDesc: "Aniversario del templo de Mens, dedicado tras desastres militares para devolver el intelecto a Roma." },
    "5-9": { status: 'NP', statusFull: "Vestalia", deity: "Vesta", deityDesc: "Diosa del fuego sagrado del estado.", festivalName: "Vestalia", festivalDesc: "Comienza la principal purificación de la casa de Vesta. Los burros de los panaderos eran adornados con panes y coronas." },
    "5-10": { status: 'N', statusFull: "Dies Nefastus", deity: "Vesta", deityDesc: "Diosa del fuego del hogar.", festivalName: "Vestalia", festivalDesc: "Continuación de los ritos privados en el santuario del Foro." },
    "5-11": { status: 'NP', statusFull: "Matralia", deity: "Mater Matuta", deityDesc: "Antigua diosa de la luz matinal.", festivalName: "Matralia", festivalDesc: "Fiesta de las matronas. Se rogaba a la diosa que protegiera a los hijos de sus hermanas por encima de los propios." },
    "5-12": { status: 'N', statusFull: "Dies Nefastus", deity: "Vesta", deityDesc: "Diosa del fuego.", festivalName: "Vestalia", festivalDesc: "Prosiguen los ritos lustrales." },
    "5-13": { status: 'NP', statusFull: "Idus", deity: "Minerva / Júpiter", deityDesc: "Diosa de los artesanos y Júpiter.", festivalName: "Quinquatrus Minusculae", festivalDesc: "La 'Pequeña Quinquatría', festival particular para los flautistas sagrados (tibicines)." },
    "5-14": { status: 'N', statusFull: "Dies Nefastus", deity: "Vesta", deityDesc: "Diosa del fuego sagrado.", festivalName: "Vestalia", festivalDesc: "Último día de labores previas a la apertura ritual total." },
    "5-15": { status: 'NP', statusFull: "Q.St.D.F.", deity: "Vesta", deityDesc: "Diosa del fuego sagrado.", festivalName: "Quando Stercum Delatum Fas", festivalDesc: "Fin oficial de la limpieza del Penus Vestae. Las cenizas purgadas eran arrastradas al Tíber o a lugares sagrados." },
    "5-16": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-19": { status: 'C', statusFull: "Dies Comitialis", deity: "Minerva", deityDesc: "Diosa de las artes y oficios.", festivalName: "Dedicación Templo Minerva", festivalDesc: "Aniversario del templo de Minerva en el monte Aventino." },
    "5-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Summanus", deityDesc: "Dios de los relámpagos nocturnos.", festivalName: "Summanalia", festivalDesc: "Sacrificio de expiación a Summanus. Se ofrecían pasteles de harina con forma de ruedas." },
    "5-21": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-23": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Fortuna", deityDesc: "Diosa de la suerte y el azar.", festivalName: "Fors Fortuna", festivalDesc: "Festividad popular a las afueras de la ciudad. El pueblo descendía en barcas por el Tíber celebrando sin restricciones." },
    "5-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Jupiter Stator", deityDesc: "Júpiter el que detiene la huida.", festivalName: "Dedicación del Templo de Jupiter Stator", festivalDesc: "Celebración del título marcial de Júpiter establecido tras las guerras en el pasado arcaico de Roma." },
    "5-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "5-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Hercules Musarum", deityDesc: "Hércules con las Musas.", festivalName: "Dedicación del Templo de Hercules Musarum", festivalDesc: "Dedicación del Templo erigido en el Circo Flaminio." },

    // --- IULIUS (JULY) ---
    "6-1": { status: 'NP', statusFull: "Kalendae", deity: "Juno", deityDesc: "Reina de los dioses.", festivalName: "Kalendae de Julio", festivalDesc: "Observancias ordinarias de las calendas." },
    "6-2": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-3": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-4": { status: 'N', statusFull: "Dies Nefastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-5": { status: 'NP', statusFull: "Poplifugia", deity: "Júpiter", deityDesc: "Dios supremo.", festivalName: "Poplifugia", festivalDesc: "La 'Huida del Pueblo'. Ritos misteriosos de origen antiquísimo vinculados a asaltos de pueblos vecinos en los albores de Roma." },
    "6-6": { status: 'N', statusFull: "Dies Nefastus", deity: "Apolo", deityDesc: "Dios de la música, sanación y profecía.", festivalName: "Ludi Apollinares", festivalDesc: "Comienzo oficial de los juegos escénicos y cívicos dedicados al dios Apolo." },
    "6-7": { status: 'NP', statusFull: "Nonae", deity: "Juno Caprotina", deityDesc: "Juno del cabrahígo.", festivalName: "Nonae Caprotinae", festivalDesc: "Fiesta de las sirvientas con batallas simuladas y banquetes. Coincide con la continuación de los Ludi Apollinares." },
    "6-8": { status: 'NP', statusFull: "Dies Nefastus", deity: "Apolo", deityDesc: "Dios de la curación.", festivalName: "Ludi Apollinares", festivalDesc: "Días consagrados al teatro y ritos a Apolo." },
    "6-9": { status: 'NP', statusFull: "Dies Nefastus", deity: "Apolo", deityDesc: "Dios de la curación.", festivalName: "Ludi Apollinares", festivalDesc: "Prosiguen los juegos de Apolo." },
    "6-10": { status: 'C', statusFull: "Dies Comitialis", deity: "Apolo", deityDesc: "Dios de la curación.", festivalName: "Ludi Apollinares", festivalDesc: "Continuación de los eventos teatrales." },
    "6-11": { status: 'C', statusFull: "Dies Comitialis", deity: "Apolo", deityDesc: "Dios de la curación.", festivalName: "Ludi Apollinares", festivalDesc: "Prosiguen los espectáculos públicos de los Ludi." },
    "6-12": { status: 'C', statusFull: "Dies Comitialis", deity: "Apolo", deityDesc: "Dios de la curación.", festivalName: "Ludi Apollinares", festivalDesc: "Penúltimo día de las festividades en honor a Apolo." },
    "6-13": { status: 'NP', statusFull: "Dies Nefastus", deity: "Apolo", deityDesc: "Dios de la curación.", festivalName: "Fin de los Ludi Apollinares", festivalDesc: "Conclusión de los Ludi dedicados a alejar plagas de la urbe." },
    "6-14": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-15": { status: 'NP', statusFull: "Idus", deity: "Cástor y Pólux / Júpiter", deityDesc: "Los Dióscuros.", festivalName: "Transvectio Equitum", festivalDesc: "Gran parada militar y religiosa en honor a los Dióscuros, revistiendo a la clase ecuestre (equites) de la República e Imperio." },
    "6-16": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Honos", deityDesc: "Dios del Honor.", festivalName: "Dedicación del Templo de Honos", festivalDesc: "Celebración cívica asociada a la deidad militar del honor." },
    "6-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día infausto cívico.", festivalName: "Dies Alliensis (Dies Ater)", festivalDesc: "Día de luto. Conmemora la derrota devastadora del ejército romano frente a los galos en la batalla del Alia (390 a.C.)." },
    "6-19": { status: 'NP', statusFull: "Lucaria", deity: "Deidades del Bosque", deityDesc: "Protectores arbolados.", festivalName: "Lucaria", festivalDesc: "Fiestas purificadoras de los bosques sagrados donde los romanos se ocultaron tras el desastre del Alia." },
    "6-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-21": { status: 'NP', statusFull: "Lucaria II", deity: "Deidades del Bosque", deityDesc: "Protectores arbolados.", festivalName: "Lucaria", festivalDesc: "Segundo día de ritos en las arboledas sagradas romanas." },
    "6-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Concordia", deityDesc: "Diosa de la armonía.", festivalName: "Dedicación del Templo de Concordia", festivalDesc: "Aniversario de otra fundación del templo." },
    "6-23": { status: 'NP', statusFull: "Neptunalia", deity: "Neptuno", deityDesc: "Dios de las aguas dulces y el mar.", festivalName: "Neptunalia", festivalDesc: "Fiesta del verano extremo buscando la intervención de las aguas divinas frente a las sequías. La gente construía cobertizos de ramas frondosas." },
    "6-24": { status: 'N', statusFull: "Dies Nefastus", deity: "Furrina", deityDesc: "Arcaica diosa de las fuentes y manantiales.", festivalName: "Furrinalia", festivalDesc: "Se ofrecían sacrificios a la olvidada diosa Furrina en su santuario del monte Janículo." },
    "6-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "6-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Fortuna Huiusce Diei", deityDesc: "La Fortuna de este Día.", festivalName: "Dedicación del Templo de Fortuna Huiusce Diei", festivalDesc: "Aniversario del templo consagrado tras batallas militares para honrar la suerte oportuna del momento." },
    "6-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },

    // --- AUGUSTUS (AUGUST) ---
    "7-1": { status: 'NP', statusFull: "Kalendae", deity: "Spes / Marte", deityDesc: "Esperanza y Dios de la Guerra.", festivalName: "Dedicaciones del 1 de Agosto", festivalDesc: "Dedicación del Templo de Spes y del Templo de Marte Ultor en la era imperial." },
    "7-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Ritos menores.", festivalName: "Supplicia Canum", festivalDesc: "Se castigaba ritualmente a los perros por no haber ladrado cuando los galos asediaron el Capitolio en el pasado lejano." },
    "7-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-5": { status: 'F', statusFull: "Nonae", deity: "Salus", deityDesc: "Diosa de la salud cívica y pública.", festivalName: "Dedicación del Templo de Salus", festivalDesc: "Aniversario del altar de la salud protectora del pueblo romano." },
    "7-6": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-7": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-8": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-9": { status: 'NP', statusFull: "Sol Indiges", deity: "Sol Indiges", deityDesc: "El Sol divino autóctono.", festivalName: "Sacrificios al Sol", festivalDesc: "Día de ritos en el cerro Quirinal con ofrendas dedicadas al Sol Indiges." },
    "7-10": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-11": { status: 'C', statusFull: "Dies Comitialis", deity: "Hércules", deityDesc: "El héroe divino.", festivalName: "Culto de Ara Maxima", festivalDesc: "Día tradicional de ritos vinculados al Altar Magno de Hércules (Ara Maxima)." },
    "7-12": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-13": { status: 'NP', statusFull: "Idus", deity: "Diana", deityDesc: "Diosa de los bosques y la naturaleza.", festivalName: "Nemoralia", festivalDesc: "Festival de la luz y de Diana celebrado en el lago Nemi, popular entre las mujeres y los esclavos." },
    "7-14": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-15": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-16": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-17": { status: 'NP', statusFull: "Portunalia", deity: "Portunus", deityDesc: "Dios de los puertos y las puertas.", festivalName: "Portunalia", festivalDesc: "Fiesta patronal de las puertas y de los accesos fluviales. Se consagraban llaves en honor al dios Portunus." },
    "7-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-19": { status: 'NP', statusFull: "Vinalia Rustica", deity: "Júpiter / Venus", deityDesc: "Dios del cielo y diosa agraria del amor.", festivalName: "Vinalia Rustica", festivalDesc: "Fiesta de apaciguamiento y bendición pre-vendimia para salvaguardar las uvas del daño estival." },
    "7-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-21": { status: 'F', statusFull: "Dies Fastus", deity: "Consus", deityDesc: "Dios de los silos subterráneos.", festivalName: "Consualia", festivalDesc: "Apertura ceremonial del altar subterráneo de Consus en el Circo Máximo y carreras de mulas coronadas con flores." },
    "7-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-23": { status: 'NP', statusFull: "Vulcanalia", deity: "Vulcano", deityDesc: "Dios del fuego devorador.", festivalName: "Vulcanalia", festivalDesc: "Rito para proteger los campos maduros del fuego del final del verano. Se arrojaban peces y presas menores a las hogueras a modo de sustituto." },
    "7-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Manes", deityDesc: "Espíritus del inframundo.", festivalName: "Mundus Patet", festivalDesc: "Primera de las tres fechas del año en que el 'Mundo' (fosa ritual del más allá) quedaba abierto, siendo un día nefasto para cualquier labor militar o política mayor." },
    "7-25": { status: 'NP', statusFull: "Opiconsivia", deity: "Ops", deityDesc: "Diosa de la abundancia almacenada.", festivalName: "Opiconsivia", festivalDesc: "Festividad secreta y sagrada celebrada en la Regia por las Vírgenes Vestales y el Pontifex Maximus en honor a la abundancia agraria." },
    "7-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-27": { status: 'NP', statusFull: "Volturnalia", deity: "Volturnus", deityDesc: "Dios del río.", festivalName: "Volturnalia", festivalDesc: "Ritos y sacrificios asociados a las aguas y vientos estacionales representados por Volturnus." },
    "7-28": { status: 'NP', statusFull: "Dies Nefastus", deity: "Sol y Luna", deityDesc: "Astros mayores.", festivalName: "Culto del Sol y la Luna", festivalDesc: "Dedicación antigua de los santuarios al Sol y la Luna situados en el Circo Máximo." },
    "7-29": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "7-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },

    // --- SEPTEMBER (SEPTEMBER) ---
    "8-1": { status: 'NP', statusFull: "Kalendae", deity: "Juno Regina", deityDesc: "Juno Reina.", festivalName: "Dedicación de Juno Regina", festivalDesc: "Dedicación oficial del templo consagrado a la protectora Juno Regina en el monte Aventino." },
    "8-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Comienzo de los masivos Juegos Romanos que se celebraban durante dos semanas en el mes de septiembre en agradecimiento a Júpiter." },
    "8-5": { status: 'F', statusFull: "Nonae", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Días de celebraciones y obras teatrales de los Juegos Romanos." },
    "8-6": { status: 'F', statusFull: "Dies Fastus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Continúan las actividades escénicas de los Juegos." },
    "8-7": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Prosiguen los juegos en la ciudad." },
    "8-8": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Obras teatrales sufragadas por ediles para disfrute del pueblo romano." },
    "8-9": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Continúan los eventos públicos." },
    "8-10": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Festividades ininterrumpidas de espectáculos romanos." },
    "8-11": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Día de espectáculos lúdicos y esparcimiento popular." },
    "8-12": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Última jornada reservada primariamente a espectáculos escénicos." },
    "8-13": { status: 'NP', statusFull: "Idus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Epulum Jovis", festivalDesc: "Banquete central de los Idus consagrado a la Tríada Capitolina; los senadores comían ritualmente junto a imágenes de los dioses." },
    "8-14": { status: 'F', statusFull: "Dies Fastus", deity: "Marte / Júpiter", deityDesc: "Deidades cívicas.", festivalName: "Equorum Probatio", festivalDesc: "Exhibición, revisión y purificación militar de los caballos romanos durante la estructura de los grandes juegos." },
    "8-15": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Comienzo del traslado de las festividades a las carreras del Circo Máximo." },
    "8-16": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Múltiples carreras de carros frente a decenas de miles de asistentes en el Circo." },
    "8-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Prosiguen las carreras organizadas por facciones ecuestres." },
    "8-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Intensificación de las competiciones del Circo." },
    "8-19": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Romani", festivalDesc: "Último día de competiciones circenses; culminación de las festividades patrias." },
    "8-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-21": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-23": { status: 'C', statusFull: "Dies Comitialis", deity: "Apolo", deityDesc: "Dios sanador.", festivalName: "Dedicación del Templo de Apolo", festivalDesc: "Celebración cívica conmemorando la dedicación del primer templo a Apolo en el Campo de Marte (431 a.C.)." },
    "8-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Venus Genetrix", deityDesc: "Venus Madre.", festivalName: "Dedicación de Venus Genetrix", festivalDesc: "Aniversario de la dedicación del templo principal en el Foro de Julio César (46 a.C.)." },
    "8-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "8-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },

    // --- OCTOBER (OCTOBER) ---
    "9-1": { status: 'NP', statusFull: "Kalendae", deity: "Fides", deityDesc: "Diosa de la Lealtad.", festivalName: "Ritos a Fides / Tigillum Sororium", festivalDesc: "Rito de consagración antigua al Tigillum Sororium (viga purificatoria) y ofrendas a la Lealtad Cívica Romana." },
    "9-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Ceres", deityDesc: "Diosa de la tierra cultivada.", festivalName: "Ieiunium Cereris", festivalDesc: "Día de ayuno religioso instaurado bajo la República en respuesta a prodigios severos y en honor a Ceres." },
    "9-5": { status: 'C', statusFull: "Dies Comitialis", deity: "Augusto / Manes", deityDesc: "El emperador divinizado y espíritus del inframundo.", festivalName: "Ludi Augustales / Mundus Patet", festivalDesc: "Inicio de los juegos imperiales en honor a Augusto. También segunda de las tres aperturas anuales del Mundus (fosa ritual al más allá): los espíritus de los muertos vagan libremente por la ciudad." },
    "9-6": { status: 'C', statusFull: "Dies Comitialis", deity: "Augusto", deityDesc: "Divus Augustus.", festivalName: "Ludi Augustales", festivalDesc: "Juegos del Augusto." },
    "9-7": { status: 'F', statusFull: "Nonae", deity: "Júpiter Fulgur / Juno", deityDesc: "Dios del trueno.", festivalName: "Ritos a Júpiter", festivalDesc: "Día tradicional de apaciguamiento estacional al dios de los rayos." },
    "9-8": { status: 'F', statusFull: "Dies Fastus", deity: "Augusto", deityDesc: "Divus Augustus.", festivalName: "Ludi Augustales", festivalDesc: "Juegos cívicos imperiales." },
    "9-9": { status: 'C', statusFull: "Dies Comitialis", deity: "Genius Publicus", deityDesc: "El Genio del pueblo romano.", festivalName: "Dedicación y Juegos", festivalDesc: "Celebración del aniversario de los Genios protectores del pueblo, entrelazada con Ludi." },
    "9-10": { status: 'C', statusFull: "Dies Comitialis", deity: "Juno Moneta", deityDesc: "Juno la Consejera.", festivalName: "Ludi Augustales", festivalDesc: "Continuación de juegos, así como conmemoración de templos atávicos." },
    "9-11": { status: 'NP', statusFull: "Meditrinalia", deity: "Meditrina / Júpiter", deityDesc: "Diosa de la curación rústica.", festivalName: "Meditrinalia", festivalDesc: "Festividad agraria para probar la vendimia. Se bebía vino mezclando mosto fresco con vino viejo como curativo de salud." },
    "9-12": { status: 'C', statusFull: "Dies Comitialis", deity: "Augusto", deityDesc: "Divus Augustus.", festivalName: "Fin Ludi Augustales", festivalDesc: "Conclusión de los juegos en honor al primer emperador." },
    "9-13": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Fons", deityDesc: "Dios de los manantiales.", festivalName: "Fontinalia", festivalDesc: "Fiesta y honores a los pozos y fuentes, engalanando todos los manantiales cívicos con guirnaldas florales de otoño." },
    "9-14": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-15": { status: 'NP', statusFull: "Idus", deity: "Marte", deityDesc: "Dios guerrero.", festivalName: "Equus October", festivalDesc: "Carrera de carros solemne final de la temporada bélica. El caballo ganador a la derecha era purificado y sacrificado al dios Marte en el Campo." },
    "9-16": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-19": { status: 'NP', statusFull: "Armilustrium", deity: "Marte", deityDesc: "Dios guerrero.", festivalName: "Armilustrium", festivalDesc: "Clausura ceremonial de las campañas militares del año. Las armas de las legiones eran purificadas y devueltas a depósito de forma sagrada." },
    "9-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-21": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-23": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "9-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Victoria", deityDesc: "Diosa de la Victoria.", festivalName: "Ludi Victoriae Sullanae", festivalDesc: "Comienzo de los juegos republicanos conmemorando la victoria de Lucio Cornelio Sila." },
    "9-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Victoria", deityDesc: "Diosa de la Victoria.", festivalName: "Ludi Victoriae Sullanae", festivalDesc: "Representaciones del éxito armado." },
    "9-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Victoria", deityDesc: "Diosa de la Victoria.", festivalName: "Ludi Victoriae Sullanae", festivalDesc: "Continuación de las festividades." },
    "9-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Victoria", deityDesc: "Diosa de la Victoria.", festivalName: "Ludi Victoriae Sullanae", festivalDesc: "Prosiguen los juegos circenses." },
    "9-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Victoria", deityDesc: "Diosa de la Victoria.", festivalName: "Ludi Victoriae Sullanae", festivalDesc: "Penúltimo día de las conmemoraciones." },
    "9-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Victoria", deityDesc: "Diosa de la Victoria.", festivalName: "Ludi Victoriae Sullanae", festivalDesc: "Último día natural del mes durante los juegos del dictador romano." },

    // --- NOVEMBER (NOVEMBER) ---
    "10-1": { status: 'NP', statusFull: "Kalendae", deity: "Juno", deityDesc: "Reina de los dioses.", festivalName: "Ludi Sullanae", festivalDesc: "Conclusión de los juegos de Sila. Honores habituales de las Calendas." },
    "10-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-3": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Inician los históricos Juegos de la Plebe, una afirmación de la identidad y libertades plebeyas." },
    "10-4": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Festividades organizadas por los ediles plebeyos." },
    "10-5": { status: 'F', statusFull: "Nonae", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Siguen las obras de teatro en las urbes." },
    "10-6": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Prosigue la actividad teatral de los Ludi." },
    "10-7": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Más celebraciones lúdicas del estado." },
    "10-8": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Manes", deityDesc: "Espíritus del inframundo.", festivalName: "Mundus Patet", festivalDesc: "Segunda apertura sagrada de la fosa al inframundo. Es el último momento anual en que los muertos vagan libremente por convención formal." },
    "10-9": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Continúa la devoción cívica teatral a Júpiter Plebeyo." },
    "10-10": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Días festivos ininterrumpidos organizados para la población." },
    "10-11": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "El programa festivo continúa." },
    "10-12": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Finaliza mayormente el circuito escénico plebeyo, a las puertas de las carreras." },
    "10-13": { status: 'NP', statusFull: "Idus", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Epulum Jovis", festivalDesc: "Importante banquete divino para Júpiter a expensas de la magistratura de la plebe." },
    "10-14": { status: 'F', statusFull: "Dies Fastus", deity: "Marte / Júpiter", deityDesc: "Deidades cívicas.", festivalName: "Equorum Probatio", festivalDesc: "Otra revisión militar ecuestre ritual celebrada durante las pausas del festival." },
    "10-15": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Feronia", deityDesc: "Diosa protectora y agraria.", festivalName: "Ludi Plebeii / Feronia", festivalDesc: "Se suman celebraciones de la diosa protectora Feronia a los espectáculos circenses." },
    "10-16": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Ludi Plebeii", festivalDesc: "Carreras ecuestres y carreras de carros frenéticas bajo techo del Circo Flaminio o Máximo." },
    "10-17": { status: 'C', statusFull: "Dies Comitialis", deity: "Júpiter", deityDesc: "Rey de los dioses.", festivalName: "Fin Ludi Plebeii", festivalDesc: "Conclusión de los Ludi Plebeii." },
    "10-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día ferial.", festivalName: "Mercatus", festivalDesc: "Apertura de las ferias comerciales que tradicionalmente sucedían tras grandes juegos continuados." },
    "10-19": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día ferial.", festivalName: "Mercatus", festivalDesc: "Negocios y mercados abiertos tras las fiestas." },
    "10-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día ferial.", festivalName: "Mercatus", festivalDesc: "Último día tradicional oficial de esta sesión ferial del año." },
    "10-21": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-23": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-25": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-29": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "10-30": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },

    // --- DECEMBER (DECEMBER) ---
    "11-1": { status: 'NP', statusFull: "Kalendae", deity: "Juno", deityDesc: "Reina divina.", festivalName: "Kalendae", festivalDesc: "Honras ordinarias de Calendas." },
    "11-2": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-3": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Bona Dea", deityDesc: "Diosa exclusiva femenina.", festivalName: "Ritos de la Bona Dea", festivalDesc: "Sacrificios místicos de bienestar auspiciados por la mujer de un magistrado; la participación masculina y el vino estaban terminantemente prohibidos." },
    "11-4": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-5": { status: 'F', statusFull: "Nonae", deity: "Fauno", deityDesc: "Deidad agreste y pastoral.", festivalName: "Faunalia Rustica", festivalDesc: "Ceremonias agrarias alegres dedicadas a Fauno para el resguardo de ganados durante el invierno incipiente." },
    "11-6": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-7": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-8": { status: 'C', statusFull: "Dies Comitialis", deity: "Tiberinus", deityDesc: "Dios tutelar fluvial.", festivalName: "Tiberinalia", festivalDesc: "Se honraba el aniversario del Templo del Dios Tíber en la isla Tiberina." },
    "11-9": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-10": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-11": { status: 'NP', statusFull: "Agonalia", deity: "Sol Indiges", deityDesc: "El Sol divino autóctono.", festivalName: "Agonalia / Septimontium", festivalDesc: "Expiación mediante sacrificio y celebración paralela en honor de las míticas primeras siete elevaciones geográficas que integraron la arcaica Roma." },
    "11-12": { status: 'EN', statusFull: "Dies Endotercissus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-13": { status: 'NP', statusFull: "Idus", deity: "Tellus", deityDesc: "La Madre Tierra.", festivalName: "Lectisternium a Ceres", festivalDesc: "Se ofrecían las primicias agrícolas a la deidad dispuesta en lechos ceremoniales agradeciendo las buenas reservas vitales conservadas." },
    "11-14": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-15": { status: 'NP', statusFull: "Consualia", deity: "Consus", deityDesc: "Dios custodio de los silos de grano.", festivalName: "Consualia de Invierno", festivalDesc: "Se destapaba su altar del Circo Máximo. Los burros y mulas eran coronados en agradecimiento general agrario." },
    "11-16": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-17": { status: 'NP', statusFull: "Saturnalia", deity: "Saturno", deityDesc: "El antiguo monarca divino agrario.", festivalName: "Saturnalia", festivalDesc: "¡Io Saturnalia! Comienza la festividad invernal de inversión de roles sociales, banquetes y goce hedonístico rememorando la Edad de Oro igualitaria." },
    "11-18": { status: 'C', statusFull: "Dies Comitialis", deity: "Saturno", deityDesc: "Dios regente.", festivalName: "Saturnalia", festivalDesc: "La ciudad queda inmersa en la entrega de pequeños obsequios (cerei y sigillaria) sin actividad judicial u hostil." },
    "11-19": { status: 'NP', statusFull: "Opalia", deity: "Ops", deityDesc: "Diosa de la providencia productiva.", festivalName: "Opalia / Saturnalia", festivalDesc: "Ofrendas consagradas a la consorte de Saturno celebrando la opulencia generada para sobrevivir las penurias." },
    "11-20": { status: 'C', statusFull: "Dies Comitialis", deity: "Saturno", deityDesc: "Rey de los dioses antiguos.", festivalName: "Saturnalia", festivalDesc: "El relajo civil absoluto prosigue. Elección tradicional en las familias del 'Rey del banquete'." },
    "11-21": { status: 'NP', statusFull: "Divalia", deity: "Angerona", deityDesc: "Diosa mística curativa y de los solsticios.", festivalName: "Divalia (Angeronalia) / Saturnalia", festivalDesc: "Celebración vinculada al solsticio con la boca de la efigie atada para exigir secreto en rituales apotropaicos y curativos invernales." },
    "11-22": { status: 'C', statusFull: "Dies Comitialis", deity: "Lares Permarini", deityDesc: "Espíritus del mar protector.", festivalName: "Saturnalia", festivalDesc: "Celebración adicional cívica por la dedicación republicana del altar a los Lares Permarini." },
    "11-23": { status: 'NP', statusFull: "Larentalia", deity: "Acca Larentia", deityDesc: "Loba nodriza divinizada.", festivalName: "Larentalia", festivalDesc: "Conclusión sombría de las Saturnales de diciembre con un rito mortuorio por los ancestros y la heroína nutricia romana en el Velabro." },
    "11-24": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-25": { status: 'NP', statusFull: "Dies Nefastus Publicus", deity: "Sol Invictus", deityDesc: "El Sol inquebrantable divino.", festivalName: "Dies Natalis Solis Invicti", festivalDesc: "Aprobada formalmente en tiempos de Aureliano, celebraba la victoria astronómica de la deidad y el retorno creciente de la luz solar anual tras el solsticio profundo." },
    "11-26": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-27": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-28": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-29": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-30": { status: 'F', statusFull: "Dies Fastus", deity: "Ninguna", deityDesc: "Día sin deidad específica." },
    "11-31": { status: 'C', statusFull: "Dies Comitialis", deity: "Ninguna", deityDesc: "Día sin deidad específica." }
};