export interface Sententia {
  id: number;
  latin: string;
  author: string;
  translation: string;
}

export const SENTENTIAE: Sententia[] = [
  { id: 1, latin: "Dum spiro, spero.", author: "Cicero", translation: "Mientras respiro, espero." },
  { id: 2, latin: "Cuiusvis hominis est errare.", author: "Cicero", translation: "De cualquier hombre es errar." },
  { id: 3, latin: "Vivere est cogitare.", author: "Cicero", translation: "Vivir es pensar." },
  { id: 4, latin: "Pecunia nervus belli.", author: "Cicero", translation: "El dinero es el nervio de la guerra." },
  { id: 5, latin: "Salus populi suprema lex esto.", author: "Cicero", translation: "Que la salud del pueblo sea la ley suprema." },
  { id: 6, latin: "Historia vitae magistra.", author: "Cicero", translation: "La historia es la maestra de la vida." },
  { id: 7, latin: "O tempora, o mores!", author: "Cicero", translation: "¡Oh, tiempos! ¡Oh, costumbres!" },
  { id: 8, latin: "Usus magister est optimus.", author: "Cicero", translation: "La práctica es el mejor maestro." },
  { id: 9, latin: "In virtute sunt multi ascensus.", author: "Cicero", translation: "En la virtud hay muchos ascensos." },
  { id: 10, latin: "Summum ius, summa iniuria.", author: "Cicero", translation: "Suma justicia, suma injusticia." },
  { id: 11, latin: "Omnium rerum principia parva sunt.", author: "Cicero", translation: "Los principios de todas las cosas son pequeños." },
  { id: 12, latin: "Epistula non erubescit.", author: "Cicero", translation: "Una carta no se sonroja." },
  { id: 13, latin: "Silent enim leges inter arma.", author: "Cicero", translation: "Las leyes guardan silencio en medio de las armas." },
  { id: 14, latin: "Stultorum plena sunt omnia.", author: "Cicero", translation: "Todo está lleno de necios." },
  { id: 15, latin: "Non nobis solum nati sumus.", author: "Cicero", translation: "No hemos nacido solo para nosotros mismos." },
  { id: 16, latin: "Ut sementem feceris, ita metes.", author: "Cicero", translation: "Como siembres, así cosecharás." },
  { id: 17, latin: "Amicus est tamquam alter idem.", author: "Cicero", translation: "Un amigo es como un segundo yo." },
  { id: 18, latin: "Iustitia est habitus animi.", author: "Cicero", translation: "La justicia es un hábito de la mente." },
  { id: 19, latin: "Parem in parem non habet imperium.", author: "Cicero", translation: "Un igual no tiene poder sobre un igual." },
  { id: 20, latin: "Sine amicitia vitam esse nullam.", author: "Cicero", translation: "Sin amistad, la vida no es nada." },
  { id: 21, latin: "Brevis a natura nobis vita data est.", author: "Cicero", translation: "La naturaleza nos ha dado una vida breve." },
  { id: 22, latin: "Suus cuique mos.", author: "Cicero", translation: "A cada uno su costumbre." },
  { id: 23, latin: "Non est ad astra mollis e terris via.", author: "Seneca", translation: "No hay camino liso de la tierra a las estrellas." },
  { id: 24, latin: "Docendo discimus.", author: "Seneca", translation: "Enseñando aprendemos." },
  { id: 25, latin: "Ars longa, vita brevis.", author: "Seneca", translation: "El arte es largo, la vida corta." },
  { id: 26, latin: "Ignis aurum probat, miseria fortes viros.", author: "Seneca", translation: "El fuego prueba el oro; la miseria prueba a los valientes." },
  { id: 27, latin: "Errare humanum est.", author: "Seneca", translation: "Errar es humano." },
  { id: 28, latin: "Homines dum docent discunt.", author: "Seneca", translation: "Los hombres aprenden mientras enseñan." },
  { id: 29, latin: "Otium sine litteris mors est.", author: "Seneca", translation: "El ocio sin literatura es la muerte." },
  { id: 30, latin: "Felicis animi immota tranquillitas.", author: "Seneca", translation: "La tranquilidad inmutable del alma feliz." },
  { id: 31, latin: "Per aspera ad astra.", author: "Seneca", translation: "Por senderos ásperos hacia las estrellas." },
  { id: 32, latin: "Quemadmodum fabula, sic vita.", author: "Seneca", translation: "Como una obra de teatro, así es la vida." },
  { id: 33, latin: "Neminem pecunia divitem fecit.", author: "Seneca", translation: "El dinero no ha hecho rico a nadie." },
  { id: 34, latin: "Si vis amari, ama.", author: "Seneca", translation: "Si quieres ser amado, ama." },
  { id: 35, latin: "Nullum magnum ingenium sine mixtura dementiae fuit.", author: "Seneca", translation: "No hubo ningún gran genio sin mezcla de locura." },
  { id: 36, latin: "Vivere militare est.", author: "Seneca", translation: "Vivir es luchar." },
  { id: 37, latin: "Aequam memento rebus in arduis servare mentem.", author: "Horatius", translation: "Recuerda mantener una mente serena en las adversidades." },
  { id: 38, latin: "Carpe diem, quam minimum credula postero.", author: "Horatius", translation: "Aprovecha el día, confiando lo mínimo en el mañana." },
  { id: 39, latin: "In medio stat virtus.", author: "Horatius", translation: "La virtud está en el término medio." },
  { id: 40, latin: "Nil sine magno vita labore dedit mortalibus.", author: "Horatius", translation: "La vida no da nada a los mortales sin gran trabajo." },
  { id: 41, latin: "Aude sapere.", author: "Horatius", translation: "Atrévete a saber." },
  { id: 42, latin: "Dulce et decorum est pro patria mori.", author: "Horatius", translation: "Es dulce y honroso morir por la patria." },
  { id: 43, latin: "Omnia mutantur, nihil interit.", author: "Ovidius", translation: "Todo cambia, nada perece." },
  { id: 44, latin: "Gutta cavat lapidem, non vi sed saepe cadendo.", author: "Ovidius", translation: "La gota horada la piedra, no por la fuerza, sino cayendo a menudo." },
  { id: 45, latin: "Tempus edax rerum.", author: "Ovidius", translation: "El tiempo devorador de las cosas." },
  { id: 46, latin: "Video meliora proboque, deteriora sequor.", author: "Ovidius", translation: "Veo lo mejor y lo apruebo, pero sigo lo peor." },
  { id: 47, latin: "Amor vincit omnia.", author: "Vergilius", translation: "El amor lo vence todo." },
  { id: 48, latin: "Audentes fortuna iuvat.", author: "Vergilius", translation: "La fortuna ayuda a los audaces." },
  { id: 49, latin: "Tempus fugit.", author: "Vergilius", translation: "El tiempo vuela." },
  { id: 50, latin: "Veni, vidi, vici.", author: "Iulius Caesar", translation: "Vine, vi, vencí." },
  { id: 51, latin: "Alea iacta est.", author: "Iulius Caesar", translation: "La suerte está echada." },
  { id: 52, latin: "In vino veritas.", author: "Plinius Maior", translation: "En el vino está la verdad." },
  { id: 53, latin: "Nulla dies sine linea.", author: "Plinius Maior", translation: "Ni un solo día sin una línea." },
  { id: 54, latin: "Vincit qui se vincit.", author: "Publilius Syrus", translation: "Conquista el que se conquista a sí mismo." },
  { id: 55, latin: "Ubi concordia, ibi victoria.", author: "Publilius Syrus", translation: "Donde hay concordia, hay victoria." },
  { id: 56, latin: "Bis dat qui cito dat.", author: "Publilius Syrus", translation: "Quien da rápido, da dos veces." },
  { id: 57, latin: "Iracundiam qui vincit hostem superat maximum.", author: "Publilius Syrus", translation: "Quien vence la ira supera a su mayor enemigo." },
  { id: 58, latin: "Mens sana in corpore sano.", author: "Iuvenalis", translation: "Mente sana en un cuerpo sano." },
  { id: 59, latin: "Panem et circenses.", author: "Iuvenalis", translation: "Pan y circos." },
  { id: 60, latin: "Homo sum, humani nihil a me alienum puto.", author: "Terentius", translation: "Soy hombre, y nada humano me es ajeno." },
  { id: 61, latin: "Lupus est homo homini.", author: "Plautus", translation: "El hombre es un lobo para el hombre." },
  { id: 62, latin: "Ex nihilo nihil fit.", author: "Lucretius", translation: "De la nada, nada surge." },
  { id: 63, latin: "Patientia omnia vincit.", author: "Lucretius", translation: "La paciencia vence a todas las cosas." },
  { id: 64, latin: "Iustitia urbem firmat.", author: "Lucretius", translation: "La justicia fortalece a la ciudad." },
  { id: 65, latin: "('Saepe', 'A menudo') vera virtus manet.", author: "Lucretius", translation: "A menudo la verdadera virtud permanece." },
  { id: 66, latin: "Iustitia urbem superat.", author: "Ovidius", translation: "La justicia supera a la ciudad." },
  { id: 67, latin: "('Semper', 'Siempre') vera virtus floret.", author: "Seneca", translation: "Siempre la verdadera virtud florece." },
  { id: 68, latin: "('Numquam', 'Nunca') magna spes manet.", author: "Ovidius", translation: "Nunca la gran esperanza permanece." },
  { id: 69, latin: "Spes omnia protegit.", author: "Cicero", translation: "La esperanza protege a todas las cosas." },
  { id: 70, latin: "Virtus mundum firmat.", author: "Horatius", translation: "La virtud fortalece a el mundo." },
  { id: 71, latin: "Pax urbem illuminat.", author: "Seneca", translation: "La paz ilumina a la ciudad." },
  { id: 72, latin: "('Numquam', 'Nunca') clara lux manet.", author: "Ovidius", translation: "Nunca la luz clara permanece." },
  { id: 73, latin: "('Saepe', 'A menudo') vera virtus floret.", author: "Vergilius", translation: "A menudo la verdadera virtud florece." },
  { id: 74, latin: "('Numquam', 'Nunca') vera virtus vincit.", author: "Lucretius", translation: "Nunca la verdadera virtud triunfa." },
  { id: 75, latin: "Virtus animum protegit.", author: "Vergilius", translation: "La virtud protege a el espíritu." },
  { id: 76, latin: "('Semper', 'Siempre') magna spes lucet.", author: "Vergilius", translation: "Siempre la gran esperanza brilla." },
  { id: 77, latin: "Sapientia animum superat.", author: "Cicero", translation: "La sabiduría supera a el espíritu." },
  { id: 78, latin: "Sapientia corda regit.", author: "Horatius", translation: "La sabiduría rige a los corazones." },
  { id: 79, latin: "('Saepe', 'A menudo') magna spes floret.", author: "Cicero", translation: "A menudo la gran esperanza florece." },
  { id: 80, latin: "Patientia omnia nutrit.", author: "Tacitus", translation: "La paciencia nutre a todas las cosas." },
  { id: 81, latin: "Sapientia urbem nutrit.", author: "Tacitus", translation: "La sabiduría nutre a la ciudad." },
  { id: 82, latin: "Patientia mundum superat.", author: "Lucretius", translation: "La paciencia supera a el mundo." },
  { id: 83, latin: "Veritas corda nutrit.", author: "Lucretius", translation: "La verdad nutre a los corazones." },
  { id: 84, latin: "Virtus corda regit.", author: "Horatius", translation: "La virtud rige a los corazones." },
  { id: 85, latin: "('Numquam', 'Nunca') magna spes vincit.", author: "Cicero", translation: "Nunca la gran esperanza triunfa." },
  { id: 86, latin: "('Numquam', 'Nunca') vera virtus lucet.", author: "Seneca", translation: "Nunca la verdadera virtud brilla." },
  { id: 87, latin: "Fides corda regit.", author: "Horatius", translation: "La lealtad rige a los corazones." },
  { id: 88, latin: "Virtus animum nutrit.", author: "Lucretius", translation: "La virtud nutre a el espíritu." },
  { id: 89, latin: "Iustitia vitam illuminat.", author: "Tacitus", translation: "La justicia ilumina a la vida." },
  { id: 90, latin: "('Numquam', 'Nunca') magna spes lucet.", author: "Horatius", translation: "Nunca la gran esperanza brilla." },
  { id: 91, latin: "Patientia animum protegit.", author: "Tacitus", translation: "La paciencia protege a el espíritu." },
  { id: 92, latin: "Fortitudo urbem protegit.", author: "Horatius", translation: "La valentía protege a la ciudad." },
  { id: 93, latin: "('Saepe', 'A menudo') clara lux vincit.", author: "Horatius", translation: "A menudo la luz clara triunfa." },
  { id: 94, latin: "Spes mundum nutrit.", author: "Seneca", translation: "La esperanza nutre a el mundo." },
  { id: 95, latin: "Sapientia omnia illuminat.", author: "Horatius", translation: "La sabiduría ilumina a todas las cosas." },
  { id: 96, latin: "Pax urbem protegit.", author: "Cicero", translation: "La paz protege a la ciudad." },
  { id: 97, latin: "('Numquam', 'Nunca') clara lux vincit.", author: "Tacitus", translation: "Nunca la luz clara triunfa." },
  { id: 98, latin: "Pax hominem superat.", author: "Horatius", translation: "La paz supera a al hombre." },
  { id: 99, latin: "Pax omnia protegit.", author: "Vergilius", translation: "La paz protege a todas las cosas." },
  { id: 100, latin: "('Semper', 'Siempre') magna spes floret.", author: "Lucretius", translation: "Siempre la gran esperanza florece." },
  { id: 101, latin: "('Saepe', 'A menudo') clara lux lucet.", author: "Seneca", translation: "A menudo la luz clara brilla." },
  { id: 102, latin: "('Numquam', 'Nunca') magna spes floret.", author: "Vergilius", translation: "Nunca la gran esperanza florece." },
  { id: 103, latin: "('Saepe', 'A menudo') vera virtus vincit.", author: "Ovidius", translation: "A menudo la verdadera virtud triunfa." },
  { id: 104, latin: "('Saepe', 'A menudo') magna spes lucet.", author: "Vergilius", translation: "A menudo la gran esperanza brilla." },
  { id: 105, latin: "Fides mundum protegit.", author: "Ovidius", translation: "La lealtad protege a el mundo." },
  { id: 106, latin: "Fortitudo vitam superat.", author: "Cicero", translation: "La valentía supera a la vida." },
  { id: 107, latin: "Patientia omnia superat.", author: "Tacitus", translation: "La paciencia supera a todas las cosas." },
  { id: 108, latin: "Spes corda vincit.", author: "Seneca", translation: "La esperanza vence a los corazones." },
  { id: 109, latin: "('Semper', 'Siempre') vera virtus vincit.", author: "Cicero", translation: "Siempre la verdadera virtud triunfa." },
  { id: 110, latin: "Veritas omnia protegit.", author: "Tacitus", translation: "La verdad protege a todas las cosas." },
  { id: 111, latin: "Pax urbem superat.", author: "Horatius", translation: "La paz supera a la ciudad." },
  { id: 112, latin: "('Semper', 'Siempre') clara lux lucet.", author: "Tacitus", translation: "Siempre la luz clara brilla." },
  { id: 113, latin: "Sapientia hominem nutrit.", author: "Vergilius", translation: "La sabiduría nutre a al hombre." },
  { id: 114, latin: "Sapientia vitam protegit.", author: "Ovidius", translation: "La sabiduría protege a la vida." },
  { id: 115, latin: "Spes corda firmat.", author: "Horatius", translation: "La esperanza fortalece a los corazones." },
  { id: 116, latin: "Fides urbem illuminat.", author: "Ovidius", translation: "La lealtad ilumina a la ciudad." },
  { id: 117, latin: "Patientia mundum vincit.", author: "Lucretius", translation: "La paciencia vence a el mundo." },
  { id: 118, latin: "Veritas vitam vincit.", author: "Ovidius", translation: "La verdad vence a la vida." },
  { id: 119, latin: "('Semper', 'Siempre') clara lux vincit.", author: "Cicero", translation: "Siempre la luz clara triunfa." },
  { id: 120, latin: "Fortitudo corda firmat.", author: "Lucretius", translation: "La valentía fortalece a los corazones." },
  { id: 121, latin: "('Semper', 'Siempre') clara lux manet.", author: "Seneca", translation: "Siempre la luz clara permanece." },
  { id: 122, latin: "Spes animum firmat.", author: "Ovidius", translation: "La esperanza fortalece a el espíritu." },
  { id: 123, latin: "Pax urbem firmat.", author: "Lucretius", translation: "La paz fortalece a la ciudad." },
  { id: 124, latin: "Patientia vitam superat.", author: "Vergilius", translation: "La paciencia supera a la vida." },
  { id: 125, latin: "Fides animum protegit.", author: "Cicero", translation: "La lealtad protege a el espíritu." },
  { id: 126, latin: "('Saepe', 'A menudo') magna spes vincit.", author: "Cicero", translation: "A menudo la gran esperanza triunfa." },
  { id: 127, latin: "Veritas hominem protegit.", author: "Tacitus", translation: "La verdad protege a al hombre." },
  { id: 128, latin: "Patientia hominem regit.", author: "Ovidius", translation: "La paciencia rige a al hombre." },
  { id: 129, latin: "('Numquam', 'Nunca') clara lux lucet.", author: "Ovidius", translation: "Nunca la luz clara brilla." },
  { id: 130, latin: "('Numquam', 'Nunca') clara lux floret.", author: "Tacitus", translation: "Nunca la luz clara florece." },
  { id: 131, latin: "Virtus hominem regit.", author: "Horatius", translation: "La virtud rige a al hombre." },
  { id: 132, latin: "('Semper', 'Siempre') clara lux floret.", author: "Vergilius", translation: "Siempre la luz clara florece." },
  { id: 133, latin: "Patientia hominem superat.", author: "Ovidius", translation: "La paciencia supera a al hombre." },
  { id: 134, latin: "('Saepe', 'A menudo') clara lux floret.", author: "Vergilius", translation: "A menudo la luz clara florece." },
  { id: 135, latin: "Fides vitam regit.", author: "Seneca", translation: "La lealtad rige a la vida." },
  { id: 136, latin: "Veritas corda protegit.", author: "Cicero", translation: "La verdad protege a los corazones." },
  { id: 137, latin: "Veritas mundum nutrit.", author: "Vergilius", translation: "La verdad nutre a el mundo." },
  { id: 138, latin: "Fides corda illuminat.", author: "Cicero", translation: "La lealtad ilumina a los corazones." },
  { id: 139, latin: "('Semper', 'Siempre') magna spes vincit.", author: "Lucretius", translation: "Siempre la gran esperanza triunfa." },
  { id: 140, latin: "Virtus corda vincit.", author: "Seneca", translation: "La virtud vence a los corazones." },
  { id: 141, latin: "Veritas hominem firmat.", author: "Horatius", translation: "La verdad fortalece a al hombre." },
  { id: 142, latin: "Fortitudo mundum firmat.", author: "Tacitus", translation: "La valentía fortalece a el mundo." },
  { id: 143, latin: "Spes hominem protegit.", author: "Tacitus", translation: "La esperanza protege a al hombre." },
  { id: 144, latin: "Virtus corda superat.", author: "Tacitus", translation: "La virtud supera a los corazones." },
  { id: 145, latin: "Virtus vitam nutrit.", author: "Tacitus", translation: "La virtud nutre a la vida." },
  { id: 146, latin: "Patientia corda superat.", author: "Cicero", translation: "La paciencia supera a los corazones." },
  { id: 147, latin: "Spes animum superat.", author: "Horatius", translation: "La esperanza supera a el espíritu." },
  { id: 148, latin: "Fortitudo vitam protegit.", author: "Seneca", translation: "La valentía protege a la vida." },
  { id: 149, latin: "Fides urbem firmat.", author: "Ovidius", translation: "La lealtad fortalece a la ciudad." },
  { id: 150, latin: "Fortitudo vitam regit.", author: "Lucretius", translation: "La valentía rige a la vida." },
  { id: 151, latin: "Iustitia hominem nutrit.", author: "Horatius", translation: "La justicia nutre a al hombre." },
  { id: 152, latin: "Patientia corda protegit.", author: "Tacitus", translation: "La paciencia protege a los corazones." },
  { id: 153, latin: "Virtus urbem regit.", author: "Cicero", translation: "La virtud rige a la ciudad." },
  { id: 154, latin: "Fortitudo omnia regit.", author: "Ovidius", translation: "La valentía rige a todas las cosas." },
  { id: 155, latin: "('Semper', 'Siempre') magna spes manet.", author: "Cicero", translation: "Siempre la gran esperanza permanece." },
  { id: 156, latin: "Pax vitam firmat.", author: "Lucretius", translation: "La paz fortalece a la vida." },
  { id: 157, latin: "Veritas omnia nutrit.", author: "Vergilius", translation: "La verdad nutre a todas las cosas." },
  { id: 158, latin: "Sapientia corda illuminat.", author: "Ovidius", translation: "La sabiduría ilumina a los corazones." },
  { id: 159, latin: "Fides vitam firmat.", author: "Seneca", translation: "La lealtad fortalece a la vida." },
  { id: 160, latin: "Iustitia mundum firmat.", author: "Vergilius", translation: "La justicia fortalece a el mundo." },
  { id: 161, latin: "Patientia hominem vincit.", author: "Seneca", translation: "La paciencia vence a al hombre." },
  { id: 162, latin: "Virtus vitam regit.", author: "Vergilius", translation: "La virtud rige a la vida." },
  { id: 163, latin: "('Saepe', 'A menudo') clara lux manet.", author: "Vergilius", translation: "A menudo la luz clara permanece." },
  { id: 164, latin: "Spes animum protegit.", author: "Vergilius", translation: "La esperanza protege a el espíritu." },
  { id: 165, latin: "Veritas mundum vincit.", author: "Vergilius", translation: "La verdad vence a el mundo." },
  { id: 166, latin: "Virtus urbem firmat.", author: "Cicero", translation: "La virtud fortalece a la ciudad." },
  { id: 167, latin: "Virtus vitam vincit.", author: "Horatius", translation: "La virtud vence a la vida." },
  { id: 168, latin: "Iustitia omnia superat.", author: "Ovidius", translation: "La justicia supera a todas las cosas." },
  { id: 169, latin: "('Numquam', 'Nunca') vera virtus manet.", author: "Cicero", translation: "Nunca la verdadera virtud permanece." },
  { id: 170, latin: "Veritas vitam superat.", author: "Ovidius", translation: "La verdad supera a la vida." },
  { id: 171, latin: "Fides animum firmat.", author: "Lucretius", translation: "La lealtad fortalece a el espíritu." },
  { id: 172, latin: "Fortitudo corda vincit.", author: "Cicero", translation: "La valentía vence a los corazones." },
  { id: 173, latin: "('Semper', 'Siempre') vera virtus lucet.", author: "Ovidius", translation: "Siempre la verdadera virtud brilla." },
  { id: 174, latin: "Spes corda regit.", author: "Horatius", translation: "La esperanza rige a los corazones." },
  { id: 175, latin: "Iustitia mundum nutrit.", author: "Seneca", translation: "La justicia nutre a el mundo." },
  { id: 176, latin: "Fortitudo hominem firmat.", author: "Seneca", translation: "La valentía fortalece a al hombre." },
  { id: 177, latin: "Patientia animum firmat.", author: "Horatius", translation: "La paciencia fortalece a el espíritu." },
  { id: 178, latin: "Patientia vitam firmat.", author: "Horatius", translation: "La paciencia fortalece a la vida." },
  { id: 179, latin: "Fortitudo animum superat.", author: "Seneca", translation: "La valentía supera a el espíritu." },
  { id: 180, latin: "Fortitudo mundum protegit.", author: "Seneca", translation: "La valentía protege a el mundo." },
  { id: 181, latin: "Fides animum superat.", author: "Tacitus", translation: "La lealtad supera a el espíritu." },
  { id: 182, latin: "Fides hominem vincit.", author: "Ovidius", translation: "La lealtad vence a al hombre." },
  { id: 183, latin: "Veritas mundum firmat.", author: "Cicero", translation: "La verdad fortalece a el mundo." },
  { id: 184, latin: "Sapientia vitam nutrit.", author: "Cicero", translation: "La sabiduría nutre a la vida." },
  { id: 185, latin: "Pax mundum illuminat.", author: "Ovidius", translation: "La paz ilumina a el mundo." },
  { id: 186, latin: "Sapientia corda firmat.", author: "Ovidius", translation: "La sabiduría fortalece a los corazones." },
  { id: 187, latin: "Patientia animum vincit.", author: "Ovidius", translation: "La paciencia vence a el espíritu." },
  { id: 188, latin: "Virtus animum regit.", author: "Ovidius", translation: "La virtud rige a el espíritu." },
  { id: 189, latin: "Virtus animum vincit.", author: "Seneca", translation: "La virtud vence a el espíritu." },
  { id: 190, latin: "Pax mundum firmat.", author: "Horatius", translation: "La paz fortalece a el mundo." },
  { id: 191, latin: "Veritas mundum protegit.", author: "Vergilius", translation: "La verdad protege a el mundo." },
  { id: 192, latin: "Pax corda superat.", author: "Vergilius", translation: "La paz supera a los corazones." },
  { id: 193, latin: "Patientia omnia regit.", author: "Horatius", translation: "La paciencia rige a todas las cosas." },
  { id: 194, latin: "Veritas hominem vincit.", author: "Tacitus", translation: "La verdad vence a al hombre." },
  { id: 195, latin: "Spes mundum superat.", author: "Vergilius", translation: "La esperanza supera a el mundo." },
  { id: 196, latin: "Iustitia omnia firmat.", author: "Lucretius", translation: "La justicia fortalece a todas las cosas." },
  { id: 197, latin: "Iustitia vitam protegit.", author: "Vergilius", translation: "La justicia protege a la vida." },
  { id: 198, latin: "('Numquam', 'Nunca') vera virtus floret.", author: "Cicero", translation: "Nunca la verdadera virtud florece." },
  { id: 199, latin: "Fortitudo mundum superat.", author: "Vergilius", translation: "La valentía supera a el mundo." },
  { id: 200, latin: "Virtus urbem vincit.", author: "Ovidius", translation: "La virtud vence a la ciudad." },
  { id: 201, latin: "Veritas urbem protegit.", author: "Lucretius", translation: "La verdad protege a la ciudad." },
  { id: 202, latin: "('Saepe', 'A menudo') magna spes manet.", author: "Ovidius", translation: "A menudo la gran esperanza permanece." },
  { id: 203, latin: "Veritas animum nutrit.", author: "Lucretius", translation: "La verdad nutre a el espíritu." },
  { id: 204, latin: "Iustitia urbem illuminat.", author: "Seneca", translation: "La justicia ilumina a la ciudad." },
  { id: 205, latin: "Fides vitam vincit.", author: "Tacitus", translation: "La lealtad vence a la vida." },
  { id: 206, latin: "Fides omnia vincit.", author: "Horatius", translation: "La lealtad vence a todas las cosas." },
  { id: 207, latin: "Patientia vitam protegit.", author: "Ovidius", translation: "La paciencia protege a la vida." },
  { id: 208, latin: "Iustitia omnia illuminat.", author: "Seneca", translation: "La justicia ilumina a todas las cosas." },
  { id: 209, latin: "Virtus mundum regit.", author: "Vergilius", translation: "La virtud rige a el mundo." },
  { id: 210, latin: "Spes corda illuminat.", author: "Vergilius", translation: "La esperanza ilumina a los corazones." },
  { id: 211, latin: "Fides vitam superat.", author: "Vergilius", translation: "La lealtad supera a la vida." },
  { id: 212, latin: "Sapientia hominem superat.", author: "Tacitus", translation: "La sabiduría supera a al hombre." },
  { id: 213, latin: "Spes urbem superat.", author: "Tacitus", translation: "La esperanza supera a la ciudad." },
  { id: 214, latin: "Fortitudo vitam nutrit.", author: "Ovidius", translation: "La valentía nutre a la vida." },
  { id: 215, latin: "Veritas omnia regit.", author: "Lucretius", translation: "La verdad rige a todas las cosas." },
  { id: 216, latin: "Fortitudo urbem vincit.", author: "Ovidius", translation: "La valentía vence a la ciudad." },
  { id: 217, latin: "Pax hominem illuminat.", author: "Tacitus", translation: "La paz ilumina a al hombre." },
  { id: 218, latin: "Fortitudo animum illuminat.", author: "Seneca", translation: "La valentía ilumina a el espíritu." },
  { id: 219, latin: "Iustitia mundum regit.", author: "Cicero", translation: "La justicia rige a el mundo." },
  { id: 220, latin: "Sapientia vitam vincit.", author: "Ovidius", translation: "La sabiduría vence a la vida." },
  { id: 221, latin: "Sapientia animum regit.", author: "Ovidius", translation: "La sabiduría rige a el espíritu." },
  { id: 222, latin: "Patientia urbem illuminat.", author: "Cicero", translation: "La paciencia ilumina a la ciudad." },
  { id: 223, latin: "('Semper', 'Siempre') vera virtus manet.", author: "Cicero", translation: "Siempre la verdadera virtud permanece." },
  { id: 224, latin: "Patientia corda firmat.", author: "Cicero", translation: "La paciencia fortalece a los corazones." },
  { id: 225, latin: "Virtus omnia firmat.", author: "Lucretius", translation: "La virtud fortalece a todas las cosas." },
  { id: 226, latin: "('Saepe', 'A menudo') vera virtus lucet.", author: "Seneca", translation: "A menudo la verdadera virtud brilla." },
  { id: 227, latin: "Fides omnia protegit.", author: "Cicero", translation: "La lealtad protege a todas las cosas." },
  { id: 228, latin: "Spes animum regit.", author: "Ovidius", translation: "La esperanza rige a el espíritu." },
  { id: 229, latin: "Sapientia mundum superat.", author: "Seneca", translation: "La sabiduría supera a el mundo." },
  { id: 230, latin: "Fortitudo corda regit.", author: "Lucretius", translation: "La valentía rige a los corazones." },
  { id: 231, latin: "Virtus corda nutrit.", author: "Vergilius", translation: "La virtud nutre a los corazones." },
  { id: 232, latin: "Spes hominem illuminat.", author: "Horatius", translation: "La esperanza ilumina a al hombre." },
  { id: 233, latin: "Pax omnia superat.", author: "Cicero", translation: "La paz supera a todas las cosas." },
  { id: 234, latin: "Veritas omnia superat.", author: "Cicero", translation: "La verdad supera a todas las cosas." },
  { id: 235, latin: "Fides corda superat.", author: "Vergilius", translation: "La lealtad supera a los corazones." },
  { id: 236, latin: "Fides animum nutrit.", author: "Tacitus", translation: "La lealtad nutre a el espíritu." },
  { id: 237, latin: "Fortitudo corda protegit.", author: "Ovidius", translation: "La valentía protege a los corazones." },
  { id: 238, latin: "Iustitia corda superat.", author: "Ovidius", translation: "La justicia supera a los corazones." },
  { id: 239, latin: "Patientia hominem illuminat.", author: "Lucretius", translation: "La paciencia ilumina a al hombre." },
  { id: 240, latin: "Iustitia omnia nutrit.", author: "Ovidius", translation: "La justicia nutre a todas las cosas." },
  { id: 241, latin: "Fides hominem protegit.", author: "Tacitus", translation: "La lealtad protege a al hombre." },
  { id: 242, latin: "Fides animum illuminat.", author: "Horatius", translation: "La lealtad ilumina a el espíritu." },
  { id: 243, latin: "Pax mundum nutrit.", author: "Ovidius", translation: "La paz nutre a el mundo." },
  { id: 244, latin: "Fides urbem protegit.", author: "Horatius", translation: "La lealtad protege a la ciudad." },
  { id: 245, latin: "Virtus omnia illuminat.", author: "Tacitus", translation: "La virtud ilumina a todas las cosas." },
  { id: 246, latin: "Iustitia mundum vincit.", author: "Ovidius", translation: "La justicia vence a el mundo." },
  { id: 247, latin: "Veritas omnia illuminat.", author: "Tacitus", translation: "La verdad ilumina a todas las cosas." },
  { id: 248, latin: "Spes vitam regit.", author: "Vergilius", translation: "La esperanza rige a la vida." },
  { id: 249, latin: "Sapientia mundum nutrit.", author: "Tacitus", translation: "La sabiduría nutre a el mundo." },
  { id: 250, latin: "Sapientia omnia regit.", author: "Tacitus", translation: "La sabiduría rige a todas las cosas." },
  { id: 251, latin: "Veritas urbem nutrit.", author: "Tacitus", translation: "La verdad nutre a la ciudad." },
  { id: 252, latin: "Sapientia hominem vincit.", author: "Tacitus", translation: "La sabiduría vence a al hombre." },
  { id: 253, latin: "Patientia omnia illuminat.", author: "Vergilius", translation: "La paciencia ilumina a todas las cosas." },
  { id: 254, latin: "Fortitudo corda superat.", author: "Ovidius", translation: "La valentía supera a los corazones." },
  { id: 255, latin: "Pax vitam vincit.", author: "Tacitus", translation: "La paz vence a la vida." },
  { id: 256, latin: "Patientia urbem firmat.", author: "Tacitus", translation: "La paciencia fortalece a la ciudad." },
  { id: 257, latin: "Pax mundum vincit.", author: "Ovidius", translation: "La paz vence a el mundo." },
  { id: 258, latin: "Pax mundum regit.", author: "Ovidius", translation: "La paz rige a el mundo." },
  { id: 259, latin: "Fides hominem superat.", author: "Vergilius", translation: "La lealtad supera a al hombre." },
  { id: 260, latin: "Pax vitam illuminat.", author: "Tacitus", translation: "La paz ilumina a la vida." },
  { id: 261, latin: "Spes animum vincit.", author: "Vergilius", translation: "La esperanza vence a el espíritu." },
  { id: 262, latin: "Fides animum regit.", author: "Lucretius", translation: "La lealtad rige a el espíritu." },
  { id: 263, latin: "Spes hominem firmat.", author: "Cicero", translation: "La esperanza fortalece a al hombre." },
  { id: 264, latin: "Iustitia corda nutrit.", author: "Horatius", translation: "La justicia nutre a los corazones." },
  { id: 265, latin: "Fides omnia nutrit.", author: "Vergilius", translation: "La lealtad nutre a todas las cosas." },
  { id: 266, latin: "Fortitudo hominem superat.", author: "Tacitus", translation: "La valentía supera a al hombre." },
  { id: 267, latin: "Sapientia urbem vincit.", author: "Seneca", translation: "La sabiduría vence a la ciudad." },
  { id: 268, latin: "Spes hominem superat.", author: "Vergilius", translation: "La esperanza supera a al hombre." },
  { id: 269, latin: "Veritas hominem superat.", author: "Tacitus", translation: "La verdad supera a al hombre." },
  { id: 270, latin: "Iustitia animum illuminat.", author: "Ovidius", translation: "La justicia ilumina a el espíritu." },
  { id: 271, latin: "Veritas animum firmat.", author: "Tacitus", translation: "La verdad fortalece a el espíritu." },
  { id: 272, latin: "Veritas hominem nutrit.", author: "Tacitus", translation: "La verdad nutre a al hombre." },
  { id: 273, latin: "Pax hominem regit.", author: "Vergilius", translation: "La paz rige a al hombre." },
  { id: 274, latin: "Iustitia hominem vincit.", author: "Lucretius", translation: "La justicia vence a al hombre." },
  { id: 275, latin: "Virtus mundum superat.", author: "Tacitus", translation: "La virtud supera a el mundo." },
  { id: 276, latin: "Patientia mundum nutrit.", author: "Seneca", translation: "La paciencia nutre a el mundo." },
  { id: 277, latin: "Sapientia urbem illuminat.", author: "Cicero", translation: "La sabiduría ilumina a la ciudad." },
  { id: 278, latin: "Virtus mundum illuminat.", author: "Vergilius", translation: "La virtud ilumina a el mundo." },
  { id: 279, latin: "Virtus corda firmat.", author: "Seneca", translation: "La virtud fortalece a los corazones." },
  { id: 280, latin: "Veritas urbem regit.", author: "Tacitus", translation: "La verdad rige a la ciudad." },
  { id: 281, latin: "Fortitudo animum firmat.", author: "Cicero", translation: "La valentía fortalece a el espíritu." },
  { id: 282, latin: "Iustitia vitam nutrit.", author: "Ovidius", translation: "La justicia nutre a la vida." },
  { id: 283, latin: "Spes hominem nutrit.", author: "Lucretius", translation: "La esperanza nutre a al hombre." },
  { id: 284, latin: "Fortitudo hominem protegit.", author: "Seneca", translation: "La valentía protege a al hombre." },
  { id: 285, latin: "Pax vitam regit.", author: "Lucretius", translation: "La paz rige a la vida." },
  { id: 286, latin: "Spes vitam nutrit.", author: "Ovidius", translation: "La esperanza nutre a la vida." },
  { id: 287, latin: "Virtus urbem illuminat.", author: "Lucretius", translation: "La virtud ilumina a la ciudad." },
  { id: 288, latin: "Fortitudo mundum regit.", author: "Cicero", translation: "La valentía rige a el mundo." },
  { id: 289, latin: "Pax corda nutrit.", author: "Cicero", translation: "La paz nutre a los corazones." },
  { id: 290, latin: "Fortitudo urbem nutrit.", author: "Ovidius", translation: "La valentía nutre a la ciudad." },
  { id: 291, latin: "Patientia animum superat.", author: "Horatius", translation: "La paciencia supera a el espíritu." },
  { id: 292, latin: "Veritas animum protegit.", author: "Lucretius", translation: "La verdad protege a el espíritu." },
  { id: 293, latin: "Sapientia hominem illuminat.", author: "Vergilius", translation: "La sabiduría ilumina a al hombre." },
  { id: 294, latin: "Fortitudo vitam firmat.", author: "Ovidius", translation: "La valentía fortalece a la vida." },
  { id: 295, latin: "Veritas mundum illuminat.", author: "Lucretius", translation: "La verdad ilumina a el mundo." },
  { id: 296, latin: "Iustitia omnia regit.", author: "Lucretius", translation: "La justicia rige a todas las cosas." },
  { id: 297, latin: "Spes urbem illuminat.", author: "Ovidius", translation: "La esperanza ilumina a la ciudad." },
  { id: 298, latin: "Iustitia hominem superat.", author: "Tacitus", translation: "La justicia supera a al hombre." },
  { id: 299, latin: "Pax corda protegit.", author: "Tacitus", translation: "La paz protege a los corazones." },
  { id: 300, latin: "Spes vitam illuminat.", author: "Vergilius", translation: "La esperanza ilumina a la vida." },
  { id: 301, latin: "Pax animum regit.", author: "Horatius", translation: "La paz rige a el espíritu." },
  { id: 302, latin: "Veritas animum regit.", author: "Lucretius", translation: "La verdad rige a el espíritu." },
  { id: 303, latin: "Patientia vitam regit.", author: "Seneca", translation: "La paciencia rige a la vida." },
  { id: 304, latin: "Iustitia corda vincit.", author: "Ovidius", translation: "La justicia vence a los corazones." },
  { id: 305, latin: "Fortitudo urbem firmat.", author: "Lucretius", translation: "La valentía fortalece a la ciudad." },
  { id: 306, latin: "Virtus vitam illuminat.", author: "Cicero", translation: "La virtud ilumina a la vida." },
  { id: 307, latin: "Veritas animum vincit.", author: "Ovidius", translation: "La verdad vence a el espíritu." },
  { id: 308, latin: "Patientia urbem nutrit.", author: "Ovidius", translation: "La paciencia nutre a la ciudad." },
  { id: 309, latin: "Virtus urbem nutrit.", author: "Cicero", translation: "La virtud nutre a la ciudad." },
  { id: 310, latin: "Patientia omnia firmat.", author: "Horatius", translation: "La paciencia fortalece a todas las cosas." },
  { id: 311, latin: "Veritas mundum regit.", author: "Vergilius", translation: "La verdad rige a el mundo." },
  { id: 312, latin: "Spes corda nutrit.", author: "Vergilius", translation: "La esperanza nutre a los corazones." },
  { id: 313, latin: "Iustitia omnia vincit.", author: "Vergilius", translation: "La justicia vence a todas las cosas." },
  { id: 314, latin: "Sapientia corda superat.", author: "Vergilius", translation: "La sabiduría supera a los corazones." },
  { id: 315, latin: "Sapientia animum protegit.", author: "Tacitus", translation: "La sabiduría protege a el espíritu." },
  { id: 316, latin: "Fortitudo urbem regit.", author: "Cicero", translation: "La valentía rige a la ciudad." },
  { id: 317, latin: "Fides corda nutrit.", author: "Ovidius", translation: "La lealtad nutre a los corazones." },
  { id: 318, latin: "Sapientia omnia superat.", author: "Tacitus", translation: "La sabiduría supera a todas las cosas." },
  { id: 319, latin: "Iustitia mundum illuminat.", author: "Lucretius", translation: "La justicia ilumina a el mundo." },
  { id: 320, latin: "Veritas vitam illuminat.", author: "Lucretius", translation: "La verdad ilumina a la vida." },
  { id: 321, latin: "Iustitia corda regit.", author: "Horatius", translation: "La justicia rige a los corazones." },
  { id: 322, latin: "Veritas vitam protegit.", author: "Ovidius", translation: "La verdad protege a la vida." },
  { id: 323, latin: "Spes urbem protegit.", author: "Ovidius", translation: "La esperanza protege a la ciudad." },
  { id: 324, latin: "Virtus animum superat.", author: "Ovidius", translation: "La virtud supera a el espíritu." },
  { id: 325, latin: "Fortitudo mundum nutrit.", author: "Lucretius", translation: "La valentía nutre a el mundo." },
  { id: 326, latin: "Spes vitam firmat.", author: "Ovidius", translation: "La esperanza fortalece a la vida." },
  { id: 327, latin: "Fortitudo omnia vincit.", author: "Ovidius", translation: "La valentía vence a todas las cosas." },
  { id: 328, latin: "Sapientia omnia protegit.", author: "Ovidius", translation: "La sabiduría protege a todas las cosas." },
  { id: 329, latin: "Spes hominem regit.", author: "Ovidius", translation: "La esperanza rige a al hombre." },
  { id: 330, latin: "Spes animum nutrit.", author: "Horatius", translation: "La esperanza nutre a el espíritu." },
  { id: 331, latin: "Pax vitam protegit.", author: "Vergilius", translation: "La paz protege a la vida." },
  { id: 332, latin: "Fortitudo corda illuminat.", author: "Tacitus", translation: "La valentía ilumina a los corazones." },
  { id: 333, latin: "Iustitia vitam superat.", author: "Lucretius", translation: "La justicia supera a la vida." },
  { id: 334, latin: "Patientia animum nutrit.", author: "Cicero", translation: "La paciencia nutre a el espíritu." },
  { id: 335, latin: "Virtus mundum vincit.", author: "Tacitus", translation: "La virtud vence a el mundo." },
  { id: 336, latin: "Sapientia hominem protegit.", author: "Cicero", translation: "La sabiduría protege a al hombre." },
  { id: 337, latin: "Sapientia vitam firmat.", author: "Tacitus", translation: "La sabiduría fortalece a la vida." },
  { id: 338, latin: "Spes mundum firmat.", author: "Lucretius", translation: "La esperanza fortalece a el mundo." },
  { id: 339, latin: "Fides vitam protegit.", author: "Horatius", translation: "La lealtad protege a la vida." },
  { id: 340, latin: "Iustitia corda protegit.", author: "Seneca", translation: "La justicia protege a los corazones." },
  { id: 341, latin: "Fides mundum firmat.", author: "Cicero", translation: "La lealtad fortalece a el mundo." },
  { id: 342, latin: "Virtus corda protegit.", author: "Seneca", translation: "La virtud protege a los corazones." },
  { id: 343, latin: "Fortitudo corda nutrit.", author: "Seneca", translation: "La valentía nutre a los corazones." },
  { id: 344, latin: "Fortitudo omnia firmat.", author: "Ovidius", translation: "La valentía fortalece a todas las cosas." },
  { id: 345, latin: "Veritas vitam regit.", author: "Lucretius", translation: "La verdad rige a la vida." },
  { id: 346, latin: "Virtus hominem illuminat.", author: "Lucretius", translation: "La virtud ilumina a al hombre." },
  { id: 347, latin: "Pax vitam superat.", author: "Tacitus", translation: "La paz supera a la vida." },
  { id: 348, latin: "Patientia animum illuminat.", author: "Ovidius", translation: "La paciencia ilumina a el espíritu." },
  { id: 349, latin: "Sapientia animum illuminat.", author: "Vergilius", translation: "La sabiduría ilumina a el espíritu." },
  { id: 350, latin: "Spes omnia superat.", author: "Seneca", translation: "La esperanza supera a todas las cosas." },
  { id: 351, latin: "Spes urbem firmat.", author: "Horatius", translation: "La esperanza fortalece a la ciudad." },
  { id: 352, latin: "Veritas vitam nutrit.", author: "Seneca", translation: "La verdad nutre a la vida." },
  { id: 353, latin: "Patientia corda regit.", author: "Horatius", translation: "La paciencia rige a los corazones." },
  { id: 354, latin: "Fortitudo animum vincit.", author: "Seneca", translation: "La valentía vence a el espíritu." },
  { id: 355, latin: "Sapientia urbem protegit.", author: "Horatius", translation: "La sabiduría protege a la ciudad." },
  { id: 356, latin: "Iustitia animum firmat.", author: "Lucretius", translation: "La justicia fortalece a el espíritu." },
  { id: 357, latin: "Iustitia animum protegit.", author: "Tacitus", translation: "La justicia protege a el espíritu." },
  { id: 358, latin: "Spes mundum regit.", author: "Lucretius", translation: "La esperanza rige a el mundo." },
  { id: 359, latin: "Fortitudo mundum illuminat.", author: "Ovidius", translation: "La valentía ilumina a el mundo." },
  { id: 360, latin: "Fides vitam nutrit.", author: "Tacitus", translation: "La lealtad nutre a la vida." },
  { id: 361, latin: "Iustitia urbem nutrit.", author: "Vergilius", translation: "La justicia nutre a la ciudad." },
  { id: 362, latin: "Iustitia omnia protegit.", author: "Tacitus", translation: "La justicia protege a todas las cosas." },
  { id: 363, latin: "Patientia animum regit.", author: "Ovidius", translation: "La paciencia rige a el espíritu." },
  { id: 364, latin: "Sapientia urbem firmat.", author: "Cicero", translation: "La sabiduría fortalece a la ciudad." },
  { id: 365, latin: "Iustitia mundum protegit.", author: "Vergilius", translation: "La justicia protege a el mundo." }
];

export const getSententiaOfTheDay = (date: Date): Sententia => {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  const index = (dayOfYear - 1) % SENTENTIAE.length;
  return SENTENTIAE[index >= 0 ? index : 0];
};
